### ISSUE TITLE
Support for gimp 2.99/3

### ISSUE THREAD

**Issue by micwoj92** [mohawk2/Alien-Gimp#4]
Gimp 2.99 provides `gimp-3.0.pc` instead of `gimp-2.0.pc`
Additionally binaries have -2.99 suffix instead of -2.0, so I don't know if that makes sense to support devel versions and just wait for stable gimp 3 release.
```
package gimp-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gimp-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gimp-2.0', required by 'virtual:world', not found
 at ./common.pl line 7.
*** can not find package gimp-2.0
*** check that it is properly installed and available in PKG_CONFIG_PATH
 at ./common.pl line 7.
Compilation failed in require at Makefile.PL line 7.
```

**Comment by mohawk2** [comment]
The only module using this distro that I know of is Gimp-Perl (https://metacpan.org/dist/Gimp), which was what motivated me to create this in the first place. I am not planning to make that support both 2 and 3, since I would expect the internal API to have changed quite a bit.

If you would like to PR changes to that and to this, so that both 2 and 3 are supported, go ahead!

**Comment by micwoj92** [comment]
API won't be stabilized until gimp 3.0 so I think it's better to wait until then.

**Comment by mohawk2** [comment]
Agreed. I will close this but feel free to open an issue when that becomes actionable!
